#
version: "3"
includes:
  buf: taskfiles/Buf.yml
  bun: taskfiles/Bun.yml
  docker: taskfiles/Docker.yml
  dokku: taskfiles/Dokku.yml
  doppler: taskfiles/Doppler.yml
  gh: taskfiles/Gh.yml
  go: taskfiles/Go.yml
  goreleaser: taskfiles/Goreleaser.yml
  log: taskfiles/Log.yml
  pkl: taskfiles/Pkl.yml
  templ: taskfiles/Templ.yaml
  wrangler: taskfiles/Wrangler.yml

silent: true
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "[onsonr] Organization Tasks"
      - task --list-all
